In [1]:
import numpy as np

In [2]:
print("welcome to python numpy related notebook")

welcome to python numpy related notebook


#Array function

In [3]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print(a1*3)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [5]:
a2>4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [6]:
from contextlib import AsyncExitStack
#array functions
np.max(a1,axis=1)

array([ 3,  7, 11])

In [7]:
np.min(a1,axis=0)#zero for col and one for row

array([0, 1, 2, 3])

In [8]:
a=np.sin(a1)
print(a)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]


In [9]:
#round/floor/cell
arr = np.ceil(np.random.rand(2, 3) * 100)
print(arr)

[[ 68.   4. 100.]
 [ 57.  20.  86.]]
