In [1]:
import numpy as np

In [2]:
print("welcome to python numpy related notebook")

welcome to python numpy related notebook


#Array function

In [3]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print(a1*3)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [5]:
a2>4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [6]:
from contextlib import AsyncExitStack
#array functions
np.max(a1,axis=1)

array([ 3,  7, 11])

In [7]:
np.min(a1,axis=0)#zero for col and one for row

array([0, 1, 2, 3])

In [8]:
a=np.sin(a1)
print(a)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]


In [9]:
#round/floor/cell
arr = np.ceil(np.random.rand(2, 3) * 100)
print(arr)

[[ 68.   4. 100.]
 [ 57.  20.  86.]]


In [ ]:
#Array slicing
arr = [10, 20, 30, 40, 50]

print(arr[1:4])     # [20, 30, 40]
print(arr[:3])      # [10, 20, 30]
print(arr[::2])     # [10, 30, 50]
print(arr[::-1])    # for ending to starting of a number

[20, 30, 40]
[10, 20, 30]
[10, 30, 50]
[50, 40, 30, 20, 10]


In [11]:
Arr=([[[0,1],[2,3]],[[4,5],[6,7]]])
print(Arr)

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [14]:


# Create a 3D NumPy array
Arr = np.array([
    [[0, 1], [2, 3]],
    [[4, 5], [6, 7]]
])

print("Original 3D Array:\n", Arr)

# 🔹 Slice examples
print("\nFirst block:\n", Arr[0])          # [[0 1] [2 3]]
print("\nSecond block:\n", Arr[1])         # [[4 5] [6 7]]
print("\nFirst row of first block:", Arr[0, 0])   # [0 1]
print("\nSingle element [1,1,0]:", Arr[1, 1, 0])  # 6

# 🔹 Print all elements (flatten)
print("\nAll elements flattened:", Arr.flatten())


Original 3D Array:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

First block:
 [[0 1]
 [2 3]]

Second block:
 [[4 5]
 [6 7]]

First row of first block: [0 1]

Single element [1,1,0]: 6

All elements flattened: [0 1 2 3 4 5 6 7]


In [15]:
#code for 4d array
array=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
array[:,2] #for particular column

array([ 2,  6, 10])

In [ ]:
array[:,0]#first column

array([0, 4, 8])

In [ ]:
array[0,:]#first row

array([0, 1, 2, 3])

In [ ]:
array[1:,1:3]#particular element

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
array[::2,::3]#only corners elements

array([[ 0,  3],
       [ 8, 11]])

In [27]:
array[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [34]:
array[1,::2]

array([4, 6])

In [36]:
array[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [38]:
array[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [40]:
a3d=np.arange(27).reshape(3,3,3)
print(a3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [41]:
a3d[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [47]:
a3d[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [44]:
a3d[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
a3d[0,1,:]

array([3, 4, 5])

In [49]:
a3d[1,:,1]

array([10, 13, 16])

In [51]:
a3d[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [60]:
a3d[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

#iteration in numpy

In [61]:
for i in arr:
    print(i)

10
20
30
40
50


In [63]:
for i in a3d:
    print(i[0])

[0 1 2]
[ 9 10 11]
[18 19 20]


In [65]:
for i in Arr:
    print(i[1])

[2 3]
[6 7]


In [ ]:
for i in np.nditer(Arr):#print all array of any dimension 
    print(i)

0
1
2
3
4
5
6
7


##Transpose


In [69]:
np.transpose(a3d)
a3d.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

#ravel

In [71]:
a3d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking


#vertical stacking

In [73]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))#concating array horizontally

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4,a5))#concating array vertically

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

spliting


In [83]:
#horizontal spliting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [85]:
#vertical spliting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [86]:
arr

[10, 20, 30, 40, 50]